### ISSUE TITLE
Redesin and implement storing aircraft model into several contexts

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea#102]
### System context scheme
System model should be described in three contexts for each aircraft type containing structural and behavioral model of the aircraft type. 
- SNS context  - containing partonomy and behavioral model of system (aircraft) from SNS import
- FHA context - containing behavioral model of system from FHA import 
- JOPA context - containing behavioral model created by the the FTA tool, e.g. creating event types for root node of experimental fault tree, i.e. fault tree not associated with a particular FHA event

### References to among contexts 
This context scheme will require the following references among contexts - this is relevant for the redesign of the JOPA entity descriptor. 

Each fault tree may have three types of fault events which contain references to resources from other contexts
- root, external reference and SNS failure events have a reference to a supertype
- root and external reference event's supertype references either
	- one event from the FHA context or
	- one event from the JOPA context
- SNS failure events reference supertype is a reference an SNS failure event type from the SNS context
- the behavior that is manifested as FHA failure is a part of the FHA context and references a component/system via the has-component from the SNS context
- the event type of a experimental root or external reference node and the behavior by which it is manifested are a part of the JOPA context. The behavior references the aircraft from the SNS context.

**Comment by kostobog** [comment]
### Implementation
	
To implement the simple context scheme 
- design and implement how to fetch contexts associated with a fault tree
- redesign and implement entity descriptor construction in fault tree dao

#### Design and implement how to fetch contexts associated with a fault tree
- find aircraft
- given the aircraft find the SNS, FHA and JOPA contexts. 
	
How contexts are associated with aircraft. Assume that `acIRI` is the `IRI` of the aircraft.
##### Design 1 - Context IRIs can be constructed by convention			
The context IRIs are constructed based on the IRI of the system as follows, acIRI-sns, acIRI-fha, acIRI-jopa

##### Design 2 - Context IRIs/ are arbitrary, they are associated with an aircraft type via triples
 2.a - using properties
```
?acIRI :has-sns-context ?snsContext; 
          :has-fha-context ?fhaContext; 
          :has-jopa-context ?jopaContext. 
```
	
2.b one property and different types

```
?acIRI :has-context ?snsContext, ?fhaContext, ?jopaContext.
?snsContext a :snsContext.
?fhaContext a :fhaContext.
?jopaContext a :jopaContext.
```

			
#### Redesign and implement entity descriptor construction in fault tree dao
- given a fault tree fetch the contexts associated with its aircraft
- construct the entity descriptor the same way replacing default context with the the contexts fetched in the first step
	
#### redesign and implement entity descriptor construction used in FaultEventDao.findEvent. 
- given a fault tree fetch the contexts associated with its aircraft
- construct the entity descriptor the same way replacing default context with the the contexts fetched in the first step

**Comment by blcham** [comment]
I like **design 1** the most as it is most intuitive to me
