### ISSUE TITLE
It is not possible to create Fault Trees anymore

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea#115]
(Tested on main branch, last commit: https://github.com/kbss-cvut/fta-fmea-ui/commit/d884b143a69d74a92a2cb97af12ade73b1066afc, I pulled all docker images).

It is not possible to create Fault Trees anymore, nor with new event nor SNS events I get 404 (`POST /fta-fmea-server/faultTrees`)

EDIT: This is also the case for updating/creating events in the FTA editor.

**Comment by LaChope** [comment]
@blcham

**Comment by blcham** [comment]
@LaChope can be closed right ?
