### ISSUE TITLE
It is not possible to create or modify an event - duplicate entity name

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea#156]
@blcham 
When trying to creating or updating an event from the fault tree, we get the following error:

![Image](https://github.com/user-attachments/assets/85597242-47ca-4a91-9c2e-4778d5c81ee7)

Server response:
`WARN  c.c.k.a.c.util.RestExceptionHandler - > handleValidationException - /fta-fmea/faultEvents/intermediate-event/inputEvents`

I am still investigating if the issue comes from the server or the client.

**Comment by kostobog** [comment]
@LaChope 
In PR #155 entity validation was unified. Fault events are now required to have a unique name.
It should work if you create an event with a different name.

**Comment by kostobog** [comment]
@LaChope 
PR #157 removes the unique name constraint for fault events.
