### ISSUE TITLE
It is not possible to create new fault tree (internal server error)

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea#96]
When create a fault tree (with existing event):

**Request:**
![Image](https://github.com/kbss-cvut/fta-fmea/assets/57750426/b89c2234-7d52-458e-87be-27e0b475375f)

**Response:**
![Image](https://github.com/kbss-cvut/fta-fmea/assets/57750426/f9bbbf44-a491-48cf-9bb3-97bc3f171fff)

**Backend:**
```
INFO  c.c.k.a.c.FaultTreeController - > create - FaultTree <null/> 
ff-iauth-demo-fta-fmea-server  | 16-05-2024 08:23:08.706 [] [thread] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/fta-fmea] threw exception [Request processing failed: java.util.NoSuchElementException: No value present] with root cause 
ff-iauth-demo-fta-fmea-server  | java.util.NoSuchElementException: No value present
ff-iauth-demo-fta-fmea-server  | 	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
```

**Comment by blcham** [comment]
@LaChope, I guess we can close this, right? If not, please provide the server log causing 500.

**Comment by LaChope** [comment]
I linked the PR so it will close when it is merged.
